### ISSUE TITLE
change to Arduino processor

### ISSUE THREAD

**Issue by dylanvaughn** [robomakery/pvc-powerchair#1]
from @SBerneberg 

The processor that will control the wheelchair has the following requirements:

2 – PWM – Speed control for right and left drive motor
2 – DIR – Direction control for right and left drive motor
2 – Analog In – The two potentiometers in the joystick
1 – UART – Rx/Tx for Bluetooth module
1 – I/O – LED Headlight control
2 – Analog In – Optional Battery Voltage and Battery current.

Looking at the Arduino offerings, only the Mega provides more that one UART.  Others have a UART but they are used for the USB interface and thus may not be used.

**Comment by miliapa** [comment]
This might help with board selection:
http://makezine.com/comparison/boards/

There are several with built in bluetooth support.

Alternatively, look for a board with a bluetooth shield available.

If your goal is to use ROS, you might want to consider a board capable of running Linux.

**Comment by bus710** [comment]
Since Arduino's basic approach doesn't accept timer interrupt, I rather pick other systems. I still need to consider affordable price tags though.

Thus, I am thinking to use STM32F0-disconvery or Mbed since both have pros such as decent price, enough performance, easy to use, and open echo system. Especially, the discovery board will be upgraded to OpenCR, which will be a part of real time ROS system soon. (so the middleware in the board will natively exchange ROS message with an Ubuntu based ROS system.)

I want to listen from you about this idea.

**Comment by dylanvaughn** [comment]
@bus710 can you give me more details on the Arduino interrupt issue?

Regarding high-level board design, I think we should have a micro linux computer (I have a [snickerdoodle](https://www.crowdsupply.com/krtkl/snickerdoodle) coming soon which we could use for this - or even something like the [Intel NUC](http://www.intel.com/content/www/us/en/nuc/overview.html)) which runs ROS and sends control instruction to arduino boards which interface with the motor drivers, etc. via the [ros_arduino_bridge](http://wiki.ros.org/ros_arduino_bridge).

Maybe we should make a diagram outlining the board setup - something like this:

https://lh3.googleusercontent.com/-_g2DF_fLgn4/V26gBZy1c4I/AAAAAAAAADA/8IWbXK99Ebge-WIxoAY7ONzaaNgUJDezACLcB/s1600/schema_JQR_5.jpg

**Comment by bus710** [comment]
1.
as you know, polling may cause timing issues to run motors.

if we use too many motors over than arduino's maximum PWM output, we have
to drive one or more motors by using timer or polling. in this case,
polling can make some delay. (if we use arduino mega, that's nice to have.)
however, i agree that arduino can be the best approach for the first step.

2.
i wish we can use NUC to avoid compatibility issue in drivers (sensor,
network, and so on.) but we also need to think about power source.

3.
yes, let's talk about a rough diagram.

SJ
