### ISSUE TITLE
Source remaining parts

### ISSUE THREAD

**Issue by dylanvaughn** [robomakery/pvc-powerchair#10]

**Comment by SBerneberg** [comment]
I have used these auto reset breakers with great success.  I usually mount them on the battery; a convenient location.  Here is a picture:
![circuit breaker](https://cloud.githubusercontent.com/assets/10985962/15333790/f5cf2358-1c1f-11e6-8b83-265d303d3094.jpg)

**Comment by SBerneberg** [comment]
I usually get these in El Cajon for about $2.25 for a 30amp breaker.

**Comment by dylanvaughn** [comment]
Find sources for these parts, purchase, and integrate into drawing and prototype v2:

* electro-mechanical circuit breaker instead of automotive fuse
* on / off switch
* charger port
* trickle charger adapter

**Comment by dylanvaughn** [comment]
Still left to buy:

* ~~Custom Arduino shield~~
* ~~Voltage divider~~
* ~~Fan~~
* ~~JST connectors~~
* Power plug
* Power jack
* ~~Hose Clamp~~

**Comment by dylanvaughn** [comment]
@rbeetem for the custom arduino shield should I get this one:

http://www.jameco.com/z/A000082-Arduino-Arduino-Uno-Proto-Shield-PCB-only-_2152438.html

which is just the bare PCB only, or this one:

http://www.jameco.com/z/A000077-Arduino-Arduino-UNO-Proto-Shield-Rev-3-assembled_2152391.html

which has a couple of things already set up?

**Comment by dylanvaughn** [comment]
@rbeetem is this what I want?  It is prime :)

https://www.amazon.com/Arduino-Proto-Shield-R3-Assembled/dp/B007QXTRNA

**Comment by rbeetem** [comment]
The bare PCB is the one I would recommend. 
http://www.jameco.com/z/A000082-Arduino-Arduino-Uno-Proto-Shield-PCB-only-_2152438.html

The other one is designed to have additional shields placed on top, which we currently have no desire to do.

**Comment by dylanvaughn** [comment]
@rbeetem I'm planning on ordering this today - does it look right?

https://www.amazon.com/gp/product/B01J1KM3RM/ref=ox_sc_act_title_2?smid=A2OVMUS055KMW5&psc=1

**Comment by rbeetem** [comment]
@dylanvaughn Looks reasonable to me.
