### ISSUE TITLE
Buy/Build LiFePO4 battery pack

### ISSUE THREAD

**Issue by dylanvaughn** [robomakery/pvc-powerchair#11]
LiFePO4

https://en.wikipedia.org/wiki/Lithium_iron_phosphate_battery

http://www.wheelchairdriver.com/BM-MK3-lithium-charging-powerchair.htm

http://www.wheelchairdriver.com/BMS.htm

**Comment by dylanvaughn** [comment]
@SBerneberg you interested in batteries? :) I would like to build what is referenced in the links above.

**Comment by SBerneberg** [comment]
I am currently making a spreadsheet of the available hubs from CONHISMOTOR.  We can look at the specs and decide which one we want to use.  Then we know the battery requirements; Voltage, Current, AHrs, etc.

**Comment by dylanvaughn** [comment]
Here is the battery selected by the Capstone team:

https://www.bioennopower.com/collections/24v-series-lifepo4-lithium-iron-phosphate-batteries/products/24v-10ah-lfp-battery-abs-blf-2410ts?variant=9845398597
