### ISSUE TITLE
high-level systems diagram

### ISSUE THREAD

**Issue by dylanvaughn** [robomakery/pvc-powerchair#24]
Create system diagram of components / electronics and their relationships

**Comment by dylanvaughn** [comment]
[V1_5 Drawing (1).pdf](https://github.com/robomakery/pvc-powerchair/files/826528/V1_5.Drawing.1.pdf)

Here is the existing drawing that @SBerneberg did

**Comment by dylanvaughn** [comment]
need to merge all drawings into a draw.io document.

**Comment by dylanvaughn** [comment]
WIP diagram can be found here:

https://github.com/robomakery/pvc-powerchair/blob/develop/docs/pvc-chair-component-diagram.png

**Comment by dylanvaughn** [comment]
Need to:

* Integrate terminal block
* On/Off switch
* Arduino Protoshield
* add wire sizing to diagram

**Comment by dylanvaughn** [comment]
Also:

* Charging Connector
* Charger
* Switch

**Comment by dylanvaughn** [comment]
Lots of progress made:

https://github.com/robomakery/pvc-powerchair/blob/develop/docs/pvc-chair-component-diagram.png

Still have some TODOs but I think it is good enough to start building against.

**Comment by rbeetem** [comment]
Updated with Arduino interfaces and pin list. 

pvc-powerchair/docs/pvc-chair-component-diagram2.png

Analog pins are in short supply if we use I2C for the OLED, could use SPI on the digital pins instead.

**Comment by dylanvaughn** [comment]
Looks good!  Can you also update the xml diagram source in github?

**Comment by rbeetem** [comment]
Updated png and xml in github.

**Comment by dylanvaughn** [comment]
last item to do on this is to rearrange diagram and add final wires to/from terminal block
