### ISSUE TITLE
Order PVC + other parts for prototype v2

### ISSUE THREAD

**Issue by dylanvaughn** [robomakery/pvc-powerchair#29]
* PVC
* Two motors (get the ones that are existing)
* Nuts and bolts
* Gearboxes
* Joystick - need to source new joystick as old one came with old custom board
* Printed parts
* Arduino Uno
* H-bridge (James Newton)
* Breakout board for arduino (James Newton)

**Comment by SBerneberg** [comment]
We have received the PVC and the motors.  Still need motor backing plate and the order from RoboShop.com.

**Comment by dylanvaughn** [comment]
We are going to try to build the motor backing plate.  I'll open another issue for that.
