### ISSUE TITLE
Cut motor plates

### ISSUE THREAD

**Issue by dylanvaughn** [robomakery/pvc-powerchair#40]
Research either getting the plates cut at makerplace or using an online service (a la Shapeways) that will cut the parts for us.

**Comment by McCAndrew88** [comment]
Getting these cut through customlasercutting.com which is actually Pololu Laser Cutting. There is a minimum order on these so I am getting 3 motor mounts. They come next Wednesday and hopefully match well with the gear boxes. I'll close this issue after I know they will work.

**Comment by McCAndrew88** [comment]
Motor mounts are cut and fit nice!
![image](https://cloud.githubusercontent.com/assets/20604274/26011098/85deeffa-3704-11e7-808a-4150f2c2144c.png)

**Comment by dylanvaughn** [comment]
@McCAndrew88 Looks good!  What was the cost?

**Comment by McCAndrew88** [comment]
$33.45 for 3 after shipping and everything. They did a really good job and it was quick, they just had a minimum so I had to order 3. Still shopping around for other places, will see what I come up with once I finish the bottom plate and box.

**Comment by dylanvaughn** [comment]
completed
