### ISSUE TITLE
Integrate joystick library with new electronics

### ISSUE THREAD

**Issue by dylanvaughn** [robomakery/pvc-powerchair#45]
Based on research done in #31 get motors working with arduino and motor driver.

**Comment by dylanvaughn** [comment]
Rob to take

**Comment by rbeetem** [comment]
user name rbeetem

**Comment by rbeetem** [comment]
Prototype build. Awaiting actual hardware for testing.

**Comment by rbeetem** [comment]
Added Arduino code to software folder. 

pvc-powerchair/software/Arduino/OpenSourceWheelChair.ino
