### ISSUE TITLE
Buy makerpipe connectors and EMC

### ISSUE THREAD

**Issue by dylanvaughn** [robomakery/pvc-powerchair#66]
Also need the heat shrink for color

**Comment by dylanvaughn** [comment]
@AkiKono could you please put in the makerpipe connector information we need to build the original frame?

**Comment by AkiKono** [comment]
Here is the number of connectors we need to build one wheelchair. (v2)

PVC WheelChair        MakerPipe 
Connector A         =     90 degree connector       = x10
Connector B         =     ------
Connector C         =     90 degree                       = x6
Connector D         =     90 degree connector      = x6
Connector E         =     T-Connector                   = x2
Connector F         =     T-Connector                   = x7

In total, 90 degree connector  x22 and T-connector x9.

The maker pipe connectors' length is different from that of PVC pipe connectors, so the length of the  electrical conduit pipes might be different from the length of the PVC pipes.

**Comment by dylanvaughn** [comment]
this was done
