### ISSUE TITLE
Research Rocker Bogie Suspension Design

### ISSUE THREAD

**Issue by dylanvaughn** [robomakery/pvc-powerchair#69]

**Comment by AkiKono** [comment]
Hi all, 

Yuriy, thank you for your continued contribution and cooperation to the powered wheelchair project :) 
We shared your PPT slides in today's bi-weekly meeting, and we appreciate a lot of your great inputs :) 
I would like to attach your PPT slides here. 
[Robo-Wheelchair_Info_rev1.pptx](https://github.com/robomakery/pvc-powerchair/files/2033949/Robo-Wheelchair_Info_rev1.pptx)

Dylan, from what I comprehended from the meeting today, I and Yuriy should now think more about the details of the frame design of rocker boogie mechanism (like which bearing to buy, how to mount wheels, etc...) and solidify the CAD model. 
And do you think we can use bent electrical conduit pipes in our rocker bogie frame design?

**Comment by yuriyFsd** [comment]
Hi Aki, 
Hope you're doing well/ 
thank you for the good feedback. Maybe there are some technical comments or questions from the team, maybe regarding additional lifting force?
I'm sorry that I cannot devote more time these days. The situation is like that: we've got an urgent project and we are in not very good financial conditions to take any risks. So I need to be fully involved in the project and don't have time for something else.. I believe that in 1.5 - 2 weeks I will have more time to get back to the wheelchair project. 
Didn't you have a chance to contact to "pipemakers" with the question about a tense load capacity of their connections?
Kind regards, Yuriy
   On Thursday, May 24, 2018, 8:39:45 AM GMT+3, Aki (Saitoh) Kono <notifications@github.com> wrote: 
 
 
Hi all,

Yuriy, thank you for your continued contribution and cooperation to the powered wheelchair project :)
We shared your PPT slides in today's bi-weekly meeting, and we appreciate a lot of your great inputs :)
I would like to attach your PPT slides here.
Robo-Wheelchair_Info_rev1.pptx

Dylan, from what I comprehended from the meeting today, I and Yuriy should now think more about the details of the frame design of rocker boogie mechanism (like which bearing to buy, how to mount wheels, etc...) and solidify the CAD model.
And do you think we can use bent electrical conduit pipes in our rocker bogie frame design?

**Comment by dylanvaughn** [comment]
Let's put this on hold for now - thanks!
