### ISSUE TITLE
Update BOM for v4

### ISSUE THREAD

**Issue by dylanvaughn** [robomakery/pvc-powerchair#70]
Based on what the capstone team is working on and what other features we want to do, update the existing bill of materials so it is up to date.

**Comment by collm2** [comment]
Hi Dylan, Let me know if you have the specific  and most updated BOM with the link to the parts on amazon or elsewhere. I can't seem to find/locate such a file. Again I could be checking in the wrong place...

**Comment by dylanvaughn** [comment]
BOM started here for v4:

https://github.com/robomakery/pvc-powerchair/blob/develop/v4/BOM.md

**Comment by dylanvaughn** [comment]
moving to emt-powerchair project
