### ISSUE TITLE
Pneumatic tires

### ISSUE THREAD

**Issue by dylanvaughn** [robomakery/pvc-powerchair#8]
research security aspects and propose new tires.

**Comment by SBerneberg** [comment]
We have talked about pneumatic tires for the chair.  This one from Northern Tool is almost double the size and thus will cause the center of gravity to rise 6".  Need to think about this.
[12_5 x 2_25 5-Spoked.pdf](https://github.com/robomakery/pvc-powerchair/files/268829/12_5.x.2_25.5-Spoked.pdf)
